# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetRooti <- function(Cov, Eye) {
    .Call('womblR_GetRooti', PACKAGE = 'womblR', Cov, Eye)
}

JointCovarianceCube <- function(WAlphas, Tau2, EyeM, Rho, M, Nu) {
    .Call('womblR_JointCovarianceCube', PACKAGE = 'womblR', WAlphas, Tau2, EyeM, Rho, M, Nu)
}

RootiLikelihoodCube <- function(JointCovariances, EyeM, M, Nu) {
    .Call('womblR_RootiLikelihoodCube', PACKAGE = 'womblR', JointCovariances, EyeM, M, Nu)
}

SIGMA <- function(Phi, TempCorInd, TimeDist, Nu) {
    .Call('womblR_SIGMA', PACKAGE = 'womblR', Phi, TempCorInd, TimeDist, Nu)
}

WAlphaCube <- function(Alpha, Z, AdjacentEdgesBoolean, W, M, Nu) {
    .Call('womblR_WAlphaCube', PACKAGE = 'womblR', Alpha, Z, AdjacentEdgesBoolean, W, M, Nu)
}

GetLogLik <- function(DatObj_List, Para_List, DatAug_List, NKeep) {
    .Call('womblR_GetLogLik', PACKAGE = 'womblR', DatObj_List, Para_List, DatAug_List, NKeep)
}

GetLogLikMean <- function(DatObj_List, Para_List, DatAug_List) {
    .Call('womblR_GetLogLikMean', PACKAGE = 'womblR', DatObj_List, Para_List, DatAug_List)
}

SamplePPD <- function(DatObj_List, Para_List, NKeep) {
    .Call('womblR_SamplePPD', PACKAGE = 'womblR', DatObj_List, Para_List, NKeep)
}

STBDwDM_Rcpp <- function(DatObj_List, HyPara_List, MetrObj_List, Para_List, DatAug_List, McmcObj_List, RawSamples, Interactive) {
    .Call('womblR_STBDwDM_Rcpp', PACKAGE = 'womblR', DatObj_List, HyPara_List, MetrObj_List, Para_List, DatAug_List, McmcObj_List, RawSamples, Interactive)
}

ThetaKrigging <- function(DatObj_List, Para_List, NKeep) {
    .Call('womblR_ThetaKrigging', PACKAGE = 'womblR', DatObj_List, Para_List, NKeep)
}

YKrigging <- function(DatObj_List, ThetaKrig, NKeep) {
    .Call('womblR_YKrigging', PACKAGE = 'womblR', DatObj_List, ThetaKrig, NKeep)
}

CholInv <- function(Cov) {
    .Call('womblR_CholInv', PACKAGE = 'womblR', Cov)
}

Inv3 <- function(A) {
    .Call('womblR_Inv3', PACKAGE = 'womblR', A)
}

makeSymm <- function(A) {
    .Call('womblR_makeSymm', PACKAGE = 'womblR', A)
}

